CREATE TABLE TB_AL_USUARIOS (
    USUARIO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'USER'
);

CREATE TABLE TB_AL_RECIPIENTES (
    RECIPIENTE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(255) NOT NULL,
    CAPACIDADE_TOTAL INT,
    CAPACIDADE_ATUAL INT DEFAULT 0,
    LOCALIZACAO VARCHAR(255)
);

CREATE TABLE TB_AL_DEPOSITOS (
    DEPOSITO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RECIPIENTE_ID BIGINT NOT NULL,
    PESO INT,
    DATA DATE,
    CONSTRAINT FK_DEPOSITO_RECIPIENTE FOREIGN KEY (RECIPIENTE_ID) REFERENCES TB_AL_RECIPIENTES(RECIPIENTE_ID)
);

CREATE TABLE TB_AL_NOTIFICACOES (
    NOTIFICACAO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RECIPIENTE_ID BIGINT NOT NULL,
    DATA DATE,
    CONSTRAINT FK_NOTIFICACAO_RECIPIENTE FOREIGN KEY (RECIPIENTE_ID) REFERENCES TB_AL_RECIPIENTES(RECIPIENTE_ID)
);

CREATE TABLE TB_AL_COLETAS (
    COLETA_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RECIPIENTE_ID BIGINT NOT NULL,
    DATA DATE,
    CONSTRAINT FK_COLETA_RECIPIENTE FOREIGN KEY (RECIPIENTE_ID) REFERENCES TB_AL_RECIPIENTES(RECIPIENTE_ID)
);