CREATE SEQUENCE SEQ_AL_USUARIOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_AL_RECIPIENTES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_AL_DEPOSITOS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_AL_NOTIFICACOES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SEQ_AL_COLETAS
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TB_AL_USUARIOS (
    USUARIO_ID INTEGER DEFAULT SEQ_AL_USUARIOS.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50) DEFAULT 'USER',
    CONSTRAINT al_email_unico UNIQUE (EMAIL)
);

CREATE TABLE TB_AL_RECIPIENTES (
    RECIPIENTE_ID INTEGER DEFAULT SEQ_AL_RECIPIENTES.NEXTVAL NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    CAPACIDADE_TOTAL INT,
    CAPACIDADE_ATUAL INT,
    LOCALIZACAO VARCHAR(255),
    CONSTRAINT PK_RECIPIENTE_ID PRIMARY KEY (RECIPIENTE_ID)
);

CREATE TABLE TB_AL_DEPOSITOS (
    DEPOSITO_ID INTEGER DEFAULT SEQ_AL_DEPOSITOS.NEXTVAL NOT NULL,
    RECIPIENTE_ID INTEGER NOT NULL,
    PESO INT,
    DATA DATE,
    CONSTRAINT PK_DEPOSITO_ID PRIMARY KEY (DEPOSITO_ID),
    CONSTRAINT FK_DEPOSITO_RECIPIENTE FOREIGN KEY (RECIPIENTE_ID) REFERENCES TB_AL_RECIPIENTES(RECIPIENTE_ID)
);

CREATE TABLE TB_AL_NOTIFICACOES (
    NOTIFICACAO_ID INTEGER DEFAULT SEQ_AL_NOTIFICACOES.NEXTVAL NOT NULL,
    RECIPIENTE_ID INTEGER NOT NULL,
    DATA DATE,
    CONSTRAINT PK_NOTIFICACAO_ID PRIMARY KEY (NOTIFICACAO_ID),
    CONSTRAINT FK_NOTIFICACAO_RECIPIENTE FOREIGN KEY (RECIPIENTE_ID) REFERENCES TB_AL_RECIPIENTES(RECIPIENTE_ID)
);

CREATE TABLE TB_AL_COLETAS (
    COLETA_ID INTEGER DEFAULT SEQ_AL_COLETAS.NEXTVAL NOT NULL,
    RECIPIENTE_ID INTEGER NOT NULL,
    DATA DATE,
    CONSTRAINT PK_COLETA_ID PRIMARY KEY (COLETA_ID),
    CONSTRAINT FK_COLETA_RECIPIENTE FOREIGN KEY (RECIPIENTE_ID) REFERENCES TB_AL_RECIPIENTES(RECIPIENTE_ID)
);